- data/scripts/creaturescripts/player/swimming.lua
- data/scripts/movements/swimming.lua
- data/scripts/talkactions/god/create_npc.lua
- data/scripts/talkactions/god/create_summon.lua
- data/scripts/talkactions/god/manage_monster.lua
- data/scripts/talkactions/player/randomoutfit.lua
- markdowns/CHANGELOG.md
Updated Swimming System to avoid some bugs.
This had some bugs; this pull request will fix them.
- Prevent players from entering the pool while in ghost mode.  
- Prevent players from logging out while in the pool.
> Updated Swimming System

- markdowns/CHANGELOG.md
- src/creatures/combat/combat.cpp
This PR fix https://github.com/opentibiabr/canary/issues/3160
Thanks to @Mortera-world
> Fix chain targets

- data/events/scripts/player.lua
- data/scripts/creaturescripts/player/login.lua
- Updated `onGainExperience` to apply Forge stack, according to https://tibia.fandom.com/wiki/Fiendish_and_Influenced_Creatures
> * Applied Forge stack

- markdowns/CHANGELOG.md
- src/creatures/combat/combat.cpp
- src/creatures/players/player.cpp
- src/creatures/players/player.hpp
- Based on https://tibia.fandom.com/wiki/Stealth_Ring, the ring will be destroyed in certain cases.
Stealth ring nos destroy
Stealth ring destroy in certain cases
> Fix stealth ring destroy

- data/XML/groups.xml
- data/scripts/talkactions/god/flags.lua
- markdowns/CHANGELOG.md
- src/creatures/players/player.cpp
- src/game/game.cpp
- src/server/network/protocol/protocolgame.cpp
- src/utils/utils_definitions.hpp
> [FEATURE] New flags

- data/XML/vocations.xml
- data/scripts/talkactions/player/promotion.lua
- markdowns/CHANGELOG.md
- markdowns/WHY_CRYSTAL_SERVER.md
- src/creatures/creatures_definitions.hpp
- src/creatures/players/player.cpp
- src/creatures/players/vocations/vocation.cpp
- src/creatures/players/vocations/vocation.hpp
- src/items/weapons/weapons.cpp
- src/server/network/protocol/protocolgame.cpp
Improved vocations.xml with new attr wandRodDamage
Please delete options that are not relevant.
> [IMPROVE] Vocations.xml

- src/lua/creature/raids.cpp
This PR fix monster loot from raids
> * Fix monster loot from raids

- data/scripts/talkactions/player/bank.lua
- markdowns/CHANGELOG.md
This fix possible crash when withdraw money via talkaction
https://github.com/opentibiabr/canary/issues/3374
> [fix] bank talkaction

- src/server/network/protocol/protocolgame.cpp
This fix allow Game Tester logout anytime
> [fix] Game tester can logout anytime

- src/game/game.cpp
This PR fixes visual effect issue when player Look In Shop
> [fix Visual effect when player look in shop

- src/creatures/creature.cpp
- src/creatures/creature.hpp
This pull  fix creature friction
> [fix] creature friction

- data-global/monster/quests/marapur/timira_the_many-headed.lua
> [fix] Timira the Many-Headed no loot drop

- data-global/startup/tables/chest.lua
This PR fixes Koshei The Deathless Quest part 1
> [fix] Koshei The Deathless Quest Part 1

- src/creatures/players/player.cpp
- src/game/game.cpp
- src/items/trashholder.cpp
Improve  the usage of create illusion from game to player Avatar
> [improve] usage of createIllusion

- data/scripts/talkactions/god/inbox_command.lua
> [fix] the inbox command

- data-global/npc/a_sweaty_cyclops.lua
thanks to @frjafopa to fix they mistake
> [fix] sweaty cyclops missing storages and talks

- data/scripts/actions/items/glooth_bag.lua
- data/scripts/talkactions/god/create_item.lua
NOTE: Loot from monsters can be sold correctly; only the command and bag are bugged. This PR will fix issue #69.
Thanks to @TheGlitchLab
> [fix] glooth equipment bug

- data-global/startup/tables/chest.lua
Fix https://github.com/opentibiabr/canary/issues/3417
> [fix] infinite reward from secret library quest

- data-global/npc/buddel.lua
- data-global/npc/buddel_helheim.lua
- data-global/npc/buddel_okolnir.lua
- data-global/npc/buddel_raider_camp.lua
- data-global/npc/buddel_tyrsung.lua
- data-global/npc/sven.lua
Changed budel priority in conditions because it wasn't working even after completing barbarian test.
> Buddel NPCs Fix

- data-global/npc/buddel.lua
- data-global/npc/buddel_helheim.lua
- data-global/npc/buddel_okolnir.lua
- data-global/npc/buddel_raider_camp.lua
- data-global/npc/buddel_tyrsung.lua
- data-global/npc/sven.lua
- data/chatchannels/scripts/guild_leaders.lua
Thanks to @Aerwix  at https://github.com/opentibiabr/canary/pull/3433
Also formated some lua files
> [fix] guild leader channel

- src/utils/tools.cpp
- tests/unit/utils/position_functions_test.cpp
thanks to @kaleohanopahala for the fix
> [fix] spell range on south walls

- src/server/network/connection/connection.cpp
- src/server/network/protocol/protocol.cpp
- src/server/network/protocol/protocol.hpp
- src/server/network/protocol/protocolgame.cpp
- src/server/network/protocol/protocolgame.hpp
This PR fixes some 14x protocol charges
> [fix] some protocol 14 charges

- src/game/game.cpp
fix https://github.com/opentibiabr/canary/issues/3313
> [fix] exori gran con damage bonus

- data-global/npc/dorian.lua
Used the correct goblet ID. Note: You must change reward ID in the map editor.
> [fix] dorian id

- data-global/npc/a_sweaty_cyclops.lua
Set the correct ID for cup of molten gold
> [fix] sweaty cyclops id

- src/crystalserver.cpp
This PR fix client evrsion showing corrict version 14.05 instead of 14.5
> [fix] client version display

- data-global/scripts/actions/mounts/mounts.lua
Corrected the taming chance when using items similar to real tibia. Corrected uniwheel and wild horse messages while taming.
> mounts-taming-chance-fix-and-msgs

- data-global/npc/a_sweaty_cyclops.lua
- data/XML/outfits.xml
- src/creatures/appearance/outfit/outfit.cpp
- src/creatures/appearance/outfit/outfit.hpp
This pull request allows the player to gain life leech, mana leech and critical hit attributes when wearing a certain outfit.
> [feature] add life leech, mana leech and critical hit to outfits

- src/creatures/players/wheel/player_wheel.cpp
This fix crash in spectators wheel
> [fix] wheel crash

- data/modules/scripts/daily_reward/daily_reward.lua
Fixed bug that add 1 excercise weapon insthead of 2. Function correction detects when an item is stackable or not to add them properly.
> daily-reward-stack-fix

- data/chatchannels/scripts/guild_leaders.lua
- data/libs/compat/compat.lua
- data/scripts/talkactions/player/war.lua
- src/creatures/interactions/chat.cpp
- src/creatures/players/cyclopedia/player_title.cpp
- src/creatures/players/player.cpp
- src/lua/functions/core/game/lua_enums.cpp
- src/lua/functions/core/game/lua_enums.hpp
- src/utils/const.hpp
- src/utils/utils_definitions.hpp
This PR improve guild and chats to use enuns insteade of static numbers, also add new talkaction !war Use the !war command in guild channel
> [improve] guild system and chat channels

- data/modules/scripts/daily_reward/daily_reward.lua
Added charges in excercise weapons
> [fix] daily reward charges

- data-global/npc/lynda.lua
Set the correct Addon Outfit looktypes for Quest
> [fix] lynda npc

- data-global/npc/lynda.lua
- data-global/npc/sandra.lua
Corrected Outfits for Addon Quest
> [fix] sandra npc

- data/items/items.xml
- data/modules/scripts/daily_reward/daily_reward.lua
- src/creatures/players/player.cpp
- src/items/functions/item/item_parse.cpp
- src/items/functions/item/item_parse.hpp
- src/items/items.hpp
- src/items/items_definitions.hpp
> [fix] amulet of loss

- src/game/game.cpp
This PR fixes potential crash in processBankAuction
> [fix] potential crash in processBankAuction

- data-global/monster/quests/feaster_of_souls/brother_worm.lua
- data-global/monster/quests/feaster_of_souls/the_unwelcome.lua
- data-global/monster/quests/feaster_of_souls/wormling.lua
- data-global/scripts/actions/bosses_levers/the_unwelcome.lua
- data-global/scripts/creaturescripts/monster/brother_worm_death.lua
Feaster of Souls Boss
*Added brother worm boss
*Added wormling summon (the unwelcome)
*Added Action to Spawn brother worm at boss room
*Added onDeath script to kill The Unwelcome when Brother Worm dies
> the-unwelcome-mechanic

- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-cmake.yml
This fixes a compilation error to avoid issues with CMake version 4.
> [fix] cmake version

- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-cmake.yml
- src/server/network/protocol/protocolgame.cpp
This fixes outfits not displaying by default. In global Tibia, these outfits are visible even if the player doesn't have them.
> [fix] golden outfit and royal costume

- data-global/npc/the_lootmonger.lua
fix https://github.com/opentibiabr/canary/issues/3481
thanks to @Sorairei
> [fix] the lootmonger remotely trade.

- data/scripts/creaturescripts/player/update_player_on_advanced_level.lua
> [fix] remove unnecessary saving on advance #114

- src/server/network/protocol/protocolgame.cpp
Fixing VIP behavior when the player dies and reappears.
> [fix] vip behaviour

- data/libs/systems/hazard.lua
- data/scripts/lib/register_monster_type.lua
Hazard Monster now are controlled inside of hazard ZoneEvent.
> fix: hazard onSpawn

- .github/workflows/build-ubuntu.yml
- .github/workflows/build-windows-cmake.yml
- CMakeLists.txt
- src/lib/thread/thread_pool.cpp
- src/lib/thread/thread_pool.hpp
- src/pch.hpp
- vcpkg.json
- vcproj/crystalserver.vcxproj
Update ThreadPool and magic_enum includes for vcpkg compatibility
> fix: updatee vcpkg to latest version

- src/creatures/creature.cpp
- src/game/game.cpp
Explanation of Optimizations
Initial Check of position.x:
- Before performing any expensive operations, we check if the position is valid (position.x != 0). This avoids unnecessary calls to getTile.
Item Creation After Validations:
- The item is only created after all validations are satisfied. This prevents the creation of unnecessary objects.
> improve: createLuaItemsOnMap function

- src/crystalserver.cpp
- src/crystalserver.hpp
- src/game/scheduling/dispatcher.cpp
More on: https://github.com/opentibiabr/canary/pull/3509
> fix: server startup loop on "Running with x threads"

- data/scripts/spells/support/avatar_of_light.lua
- data/scripts/spells/support/avatar_of_nature.lua
- data/scripts/spells/support/avatar_of_steel.lua
- data/scripts/spells/support/avatar_of_storm.lua
Corrected the neverending display of Looktypes when using the spells.
> fix: avatars looktype

- data-global/npc/sam.lua
> sam-fix-what-a-foolish-quest

- data-global/npc/alesar.lua
- data-global/npc/haroun.lua
- data-global/npc/nah_bob.lua
- data-global/npc/yaman.lua
Fixed storages for a correct interaction in quest. This code was taken from canary I am not the author of this correction. It was made by ricardokaky. Thank You!
> fix: djinn quest

- data/scripts/talkactions/god/storage.lua
I created an useful command for admins to debug quests, items, mechanics, etc. Just set the storage in a player to start testing.
> feat: set storage debug command

- data-global/npc/sam.lua
- data-global/npc/the_bone_master.lua
- data-global/npc/the_dream_master.lua
Allow to enter Knightwatch Tower After the first achievement as in real tibia insthead of finish the whole quest.
> fix: dreamer's challenge quest

- data/libs/functions/creature.lua
> fix: doors console error

- src/server/server.cpp
- ServicePort::open now supports binding to IPv4 addresses, IPv6 addresses, or domain names as specified in the configuration.
- If the 'IP' config value is an IPv4 address, the server binds to that IPv4 address.
- If the 'IP' config value is an IPv6 address, the server binds to that IPv6 address.
- If the 'IP' config value is a domain name, it is resolved and the server prefers binding to an IPv6 address if available, otherwise falls back to IPv4.
- Fixed a compilation error caused by use of the ternary operator with different endpoint types (address_v4 vs address_v6). Now, the code clearly distinguishes between the types with explicit branching.
- Added error handling for cases where address resolution fails.
> fix: add support for IPv4, IPv6, and domain names in ServicePort::open; fix endpoint type error

- data-global/npc/angus.lua
- data-global/npc/mortimer.lua
The NPC wasn't replying properly because of the format. Also fixed the storages properly to advance in quest.
> fix: spectral stone mission

- data-global/monster/quests/ferumbras_ascension/traps/void.lua
- data-global/scripts/quests/ferumbras_ascension/actions_ferumbras_lever.lua
- data-global/scripts/quests/ferumbras_ascension/creaturescripts_rift_invader_death.lua
- data-global/scripts/quests/ferumbras_ascension/movements_vortex.lua
This PR fixes ferumbras quest, thanks to @Mckay666 for the files
> fix: ferumbras quest

- data-global/scripts/actions/other/fluids.lua
This PR fix fluid issues, thanks to @vllworldbuilding
> fix: fluids descriptions

- data/XML/mounts.xml
- data/XML/outfits.xml
- src/creatures/appearance/mounts/mounts.cpp
- src/creatures/appearance/mounts/mounts.hpp
- src/creatures/appearance/outfit/outfit.cpp
- src/creatures/appearance/outfit/outfit.hpp
This PR fixes the issue where outfits and mounts were not functioning correctly due to being treated as double values
> fix: outfits and mounts attributes

- src/game/game.cpp
> fix: global stow

- data-crystal/ACTION_IDS.md
- data-crystal/npc/carpetman.lua
- data-crystal/startup/tables/writeable.lua
In ACTION_IDS and related scripts
> fix: update references from Premium Island to Thyranox

- data/events/scripts/party.lua
This PR fixes some issues related with playerId
> fix: party disband

- src/io/functions/iologindata_save_player.cpp
Reduce memory allocations when saving items
> improve: items saving

- data-global/monster/quests/primal_ordeal_quest/the_end_of_days.lua
- data/scripts/creaturescripts/player/death.lua
1.- Changed Class of The End of Days to elemental. 
2.- Added teleport to temple in death to fix death loop in magma bubble battle. (Fix by Lacory, not active in our github as contributor)
> fix: primal ordeal quest

- data/scripts/talkactions/god/effect.lua
An useful command if you are creating scripts and want to check how to effects looks like.
> feat: check effect talkaction

- data-global/monster/quests/primal_ordeal_quest/the_primal_menace.lua
- data-global/scripts/actions/bosses_levers/the_primal_manace.lua
- data/scripts/talkactions/god/effect.lua
This PR fixes issue https://github.com/zimbadev/crystalserver/issues/266
Note: Make sure your acocunt and your character are not a Game Tester or God Account
Make sure players have acocunt type 1 and group 1
> fix: The Primal Menace disabling coodown

- data/items/items.xml
Updated item name and decay in order to make it work properly for other players.
> fix: update ConchShell Quest

- data-global/npc/ambassador manop.lua
- data-global/scripts/quests/the_way_of_the_monk/actions_dawnport_shrines.lua
- data-global/scripts/quests/the_way_of_the_monk/monk_shrine_reset.lua
- data/items/items.xml
This PR remove addEvent and transformOnUse
item transformation is controlled by action
> fix: shrine from monk quest

- .github/workflows/analysis-reviewdog-cppcheck.yml
- .github/workflows/analysis-reviewdog.yml
Add it again for some testing purpose
> fix: add missing actions

- data/libs/functions/player.lua
More info at https://github.com/opentibiabr/canary/pull/3569
thanks to @gabrielew
> fix: familidar cooldown

- data/scripts/lib/register_achievements.lua
Added new achievements
July 01, 2024
Summer Update 2024
July 01, 2024
Summer Update 2024
July 01, 2024
Summer Update 2024
July 01, 2024
Summer Update 2024
July 01, 2024
Summer Update 2024
July 01, 2024
Summer Update 2024
November 25, 2024
Winter Update 2024
April 08, 2025
Monk Vocation Update
April 08, 2025
Monk Vocation Update
April 08, 2025
Monk Vocation Update
November 25, 2024
Winter Update 2024
July 01, 2024
Summer Update 2024
> fix: missing achievements

- data-global/npc/frafnar.lua
There is an error in the logic of the progress of this quest. The error was that the quest only progress if you joke about Bolfona's cake delivery, which is confusing and stuck players. Now progress unless you report about Bolfona delivery and it's optional to say if you mentioned him as the one who sent the cake to Bolfona.
> fix frafnar npc

- data-global/scripts/quests/the_secret_library_quest/movement_teleport.lua
This teleport leads to the boss "The Scourge of Oblivion" There are some missing mechanics in this boss that I will create and share soon.
> Fix: Secret Library Teleport

- data-global/scripts/quests/the_rookie_guard/mission11_sweet_poison.lua
This fix ensures to proceed properly into the next stage of the quest, else u get stuck.
> fix Sweet Poison mission

- src/creatures/creature.cpp
This PR fixes issues related to zones, including the infinite death loop in Magma Bubble.
> fix: critical zones related issues

- data-global/raids/raids.xml
To avoid raids flood in server I set real tibia more like timers in executions for raids.
> fix: update raids delay

- data-global/scripts/quests/primal_ordeal_quest/magma_bubble_fight.lua
> fix: Magma Bubble

- data-global/npc/a_dead_bureaucrat1.lua
- data-global/npc/a_dead_bureaucrat2.lua
- data-global/npc/a_dead_bureaucrat3.lua
- data-global/npc/a_dead_bureaucrat4.lua
Just a proposal, average open tibia player and regular tibia player gets stuck in this part. It is really annoying. This isn't real tibia content but I think it would enhance the gameplay in this part of all open tibia players.
> proposal: bribe bureaucrats

- src/creatures/npcs/npc.cpp
Remove unnecessary vector heap-allocation
> optimize: NPC getRandomStep

- data-global/npc/a_dead_bureaucrat1.lua
- data-global/npc/a_dead_bureaucrat2.lua
- data-global/npc/a_dead_bureaucrat3.lua
- data-global/npc/a_dead_bureaucrat4.lua
- data/scripts/spells/attack/chained_penance.lua
- data/scripts/spells/attack/flurry_of_blows.lua
- data/scripts/spells/attack/greater_flurry_of_blows.lua
- src/io/io_wheel.cpp
This PR apply balancing charges from
https://www.tibia.com/news/?subtopic=newsarchive&id=8452&fbegind=16&fbeginm=7&fbeginy=2025&fendd=15&fendm=8&fendy=2025&flist=11111111
> fix: monk balancing charges

- data-global/scripts/quests/ferumbras_ascension/creaturescripts_bosses_kill.lua
- data-global/scripts/quests/ferumbras_ascension/creaturescripts_rift_invader_death.lua
- Thank to [Pablodotnet](https://github.com/Pablodotnet) https://github.com/opentibiabr/canary/pull/3646
> fix: ferumbras ascension quest

- data-global/scripts/quests/cults_of_tibia/movements_boss_timer.lua
- Thanks to [Pablodotnet](https://github.com/Pablodotnet) https://github.com/opentibiabr/canary/pull/3657
> fix: add boss cooldown system for cults of tibia with time localization and teleport logic

- data-global/monster/demons/herald_of_gloom.lua
- Thanks to [gabrielew](https://github.com/gabrielew) https://github.com/opentibiabr/canary/pull/3627
> fix: resolve invalid outfitMonster configuration causing "Monster does not exist" error

- src/creatures/players/player.cpp
- src/creatures/players/player.hpp
- src/io/functions/iologindata_load_player.cpp
- src/server/network/protocol/protocolgame.cpp
- src/server/network/protocol/protocolgame.hpp
This PR fixes the backpack saving order and resolves the issue with missing containers.
Also removed deprecated sendHotkeyPreset
https://github.com/user-attachments/assets/0a39cba4-539c-444a-b78c-b4d5762d3f25
> fix: missing container and backpack positons

- src/game/game.cpp
- src/game/game.hpp
- src/server/network/protocol/protocolgame.cpp
I reverted this PR in the main branch and created this new PR until we have a fix for the possible crash.
If you test this PR, please post the results there to help us.
> feat: quickloot with hotkey

- data/scripts/actions/objects/cask_and_kegs.lua
when using the empty bottle in the barrel the item is not transformed.
how to reproduce.
use an empty flask in a keg
(ex: 284 > 25911)
> fix: use Empty Flask in Keg (error line 29)
