zimbadev/crystalserver

src/creatures/combat/spells.cpp, src/creatures/creature.hpp, src/creatures/players/player.cpp
Fixed getCorpse behavior in different situations.
09:50 You see a dead human (Vol:10).
You recognize Knight. He was killed by Paladin and a brachiodemon, a brachiodemon, an infernal phantom, an infernal demon, an infernal demon, an infernal phantom, an infernal demon, a brachiodemon, an infernal demon, an infernal phantom and a brachiodemon.
Different situations:
by player
10:06 You see a dead human (Vol:10).
You recognize Knight. He was killed by Paladin.
by player and monsters
10:09 You see a dead human (Vol:10).
You recognize Knight. He was killed by Paladin and a brachiodemon.
by player and they summons
10:16 You see a dead human (Vol:10).
You recognize Knight. He was killed by Master Chain and a fire elemental summoned by Master Chain.
=> * Fix Player::getCorpse

src/game/game.cpp
Fix damage sending 
A rat loses 332 hitpoints due to your attack.
A rat loses 20 hitpoints due to your attack.
=> * Fixed sending damage higher then monster health

src/game/game.cpp
Fixed mana drian not displayed in Input Damage Analzyer
Input Analyzer does not display mana drain
Input Analyzer display mana drain
Every monster that drain players mana can be tested
=> * Fix mana drain not displayed in Input Analyzer

src/creatures/combat/combat.cpp, src/creatures/combat/combat.hpp, src/creatures/combat/condition.cpp, src/creatures/combat/condition.hpp, src/creatures/players/player.cpp, src/creatures/players/player.hpp
This PR introduces a mechanism for handling a condition within the combat system. The changes include implementing the condition's logic, integrating it into the combat flow, and updating the player class to support immunity to this condition.
=> Fix: root condition implementation

src/game/game.cpp
New Boss Points Highscore Query. Now the query avoid all the characters from account 1. Removing all the Sample from highscores or Characters on account id 1
=> Fix Highscores and new Query

data/migrations/51.lua, markdowns/CHANGELOG.md, src/io/functions/iologindata_save_player.cpp, src/io/functions/iologindata_save_player.hpp, src/lua/functions/creatures/player/player_functions.cpp
This feature implements a name change system that saves old player names in a new database table, `player_oldnames`.
Dont save player old names
Save old player names to database
Tested with store name changer
**Test Configuration**:
- Server Version: 4.1.3
- Client: 14.05
- Operating System: Windows
=> [FEATURE] Name Change to save old player Names

data-crystal/npc/lara.lua, data-crystal/npc/sherlock.lua, data-crystal/scripts/actions/objects/imbuement_shrine.lua, data-crystal/world/world-monster.xml, data-crystal/world/world-npc.xml, data/npclib/npc_system/modules.lua
=> [FEATURE] Update Crystal Server Map

src/items/item.cpp, src/items/item.hpp
This enhances the management of imbuement slots by verifying whether a slot is empty before retrieving imbuement details.  
Previously, the `getImbuementInfo` function would return an invalid imbuement even for empty slots. Now, it ensures that only valid imbuements are processed.
=> * Fix imbuement empty slot

data/items/items.xml, data/scripts/movements/trap.lua
NOTE: Update your map to the latest world.7z in the world folder.  
Alternatively, edit your map by replacing all IDs: change 2148 to 2147 and 44530 to 44529.
=> [fix] map issues with traps

data-global/lib/quests/soul_war.lua, data-global/scripts/world_changes/spawns_npc_by_time.lua, data-global/world/world-npc.xml
This fix addresses the issue where NPCs were being duplicated due to incorrect handling of their addition and removal. Now, there is no longer a need for the NPCs to be defined in the XML file, as they are created dynamically through the script when the server starts.
thanks to @LeoTKBR
=> [fix] spawns npc by time

src/game/game.cpp, src/game/game.hpp, src/server/network/protocol/protocolgame.cpp
Previously, the "disable mount" option in the outfit window was not functioning correctly, allowing players to dismount only via the CTRL + R shortcut.
This fix adds a proper check for the `isMounted` value to ensure the mount state is correctly handled through the outfit window.
=> [fix] disable mount in outfit window

src/creatures/creature.cpp, src/game/game.cpp, src/game/game.hpp
[NÃO TESTADO]
- Removendo o `Game::afterCreatureZoneChange` que está sendo chamado em `Creature::changeHealth` pois ele já está sendo chamado em `Game::removeCreature`.
- Removendo `Game::executeDeath` e `setDifference` que não estão sendo usados mais.
- Usando `std::views::filter` no lugar de` setDifference` (o correto seria fazer um teste de performance entre os dois).
- Removendo a cópia desnecessária de creature em `Game::afterCreatureZoneChange`
- Removendo loop duplicado para zones
-----------------
[UNTESTED]
- Removing Game::afterCreatureZoneChange, which is being called in Creature::changeHealth, since it is already being called in Game::removeCreature.
- Removing Game::executeDeath and setDifference, which are no longer being used.
- Using std::views::filter instead of …
=> improve: creature zone change

src/creatures/players/player.cpp, src/items/item.cpp, src/items/item.hpp
Previously, the addImbuement function was called after the stats were applied, which allowed players to exploit the system using bot scripts to stack multiple imbuements without proper validation.
This fix moves the addImbuement call earlier in the logic and checks its return value to ensure the imbuement was successfully applied before proceeding to update the player's stats.
=> fix: ensure imbuement is applied before setting stats to player

config.lua.dist, src/server/network/protocol/protocolgame.cpp, src/server/network/protocol/protocolgame.hpp
Creature removal is now much faster as we avoid unnecessarily iterating over large sets. 
The code is more organized and easier to understand, with clear helper functions.
The solution is scalable and can easily handle larger limits of known creatures if needed. The optimized code above significantly improves the performance and maintainability of the known creatures cache system in OTServ.
It resolves issues related to unnecessary iteration and inefficient data structures, ensuring faster and more reliable operation.
=> perf: optimized the checkCreatureAsKnown function

data-global/lib/quests/soul_war.lua, data/events/scripts/player.lua, data/libs/systems/hazard.lua
This PR introduces a fix and enhancement for the experience boost system related to the Soul War quest. Specifically, it ensures that the player's taint level is correctly factored into the experience calculation when defeating monsters listed in SoulWarQuest.bagYouDesireMonsters.
thanks to @FelipePaluco
=> fix: add taint experience boost for Soul War monsters

data/modules/scripts/gamestore/init.lua
By applying this modification, it will function correctly, and the correct amount of exp boost will be visually charged.
ty @LeoTKBR
=> fix: gamestore exp boost price

src/creatures/creature.cpp, src/game/game.cpp
Now you can move items to a container and it does not auto scroll
thanks to @jpaulooliveira
=> fix: container auto scroll while moving items

src/creatures/players/player.cpp, src/server/network/protocol/protocolgame.cpp
Initial implementation of the new AddPlayerSkills to support the updated protocol structure.
🔍 Things to review and improve:
The following still needs to be checked and properly calculated:
- Damage/Healing
- Attack Value
- Converted Damage
msg:addDouble() requires a precision parameter. I'm currently using 5 for testing purposes — this seems to work, but it's unclear for me if it's the ideal value for every case.
It may also be worth refactoring the function for better readability and maintainability.
⚠️ Notes:
This is an initial commit for the feature and still needs polishing.
=> feature: adapt AddPlayerSkills to 14.12 protocol

data/scripts/spells/house/kick.lua
Added House Tile Check to avoid flood console with errors when using outside of a house.
=> fix: kick player house spell

data-global/monster/quests/feaster_of_souls/brother_worm.lua, data-global/monster/quests/feaster_of_souls/the_unwelcome.lua
Upon Killing Brother Worm the kill counts for the Unwelcome as It's impossible to kill the Unwelcome without killing the brother worm.
=> fix: the unwelcome bosstiary

data-global/npc/sam.lua, data-global/scripts/quests/what_a_foolish_quest/action_contract.lua
Fixed storage logic in Sam contract mission and the contract item check in order to match bozo NPC original design.
=> fix: what a foolish quest storage

data-global/scripts/actions/other/destroy.lua
Now you can use all weapons to destroy objects. If I missed some weapon IDs please let me know. It also works in quests, like for destroying energy barrier in threatened dreams quest.
=> fix: destroy obejcts

data-global/scripts/quests/heart_of_destruction/actions_final_lever.lua
The Spark of Destruction had a 2 in the initial source. I have no idea why, well I fixed it to properly call the monster script from our datapack because "spark of destruction2" does not exists.
=> fix: heart of destruction quest final lever

data-global/scripts/quests/heart_of_destruction/actions_anomaly_lever.lua, data-global/scripts/quests/heart_of_destruction/actions_eradicator_lever.lua, data-global/scripts/quests/heart_of_destruction/actions_outburst_lever.lua, data-global/scripts/quests/heart_of_destruction/actions_realityquake_lever.lua, data-global/scripts/quests/heart_of_destruction/actions_rupture_lever.lua
Map lacks of action IDs I changed the codes to trigger via lever positions to allow play in boss fights. Also fixed some wrong coords. I moved the files from actions to quests folder.
=> fix: heart of destruction bosses

data-global/scripts/quests/heart_of_destruction/movements_ice_crack.lua, data/items/items.xml
The ice hole was creating over and over again in the same spot every time. The script now check if there's a hole there and auto deletes itself after 10 seconds.
=> fix: heart of destruction tile

src/game/game.cpp
This PR fix crash while moving player to a teleport, example: Soul War teleports
=> fix: crash while moving player in diagonal to a teleport

src/creatures/combat/combat.cpp
This adjustment resolves an issue where certain abilities, particularly those affecting an area (AoE), would sometimes fail to inflict any harm if the individual casting the ability and the intended recipient were the sole beings visible on the screen. This happened as a result of incomplete transmission of vital impact values when only a single subject was located within the zone.
=> fix: critical damage in single target

data-crystal/scripts/special/ferumbras_tower.lua, data-global/scripts/quests/soulpit/soulpit_fight.lua
- When a player died in the soulpit, they apparently weren't removed from the zone, so every time these functions ran, the player was teleported to the soulpit exit. In other words, every time someone soulpitted,
anyone who died inside was teleported to the exit.
=> fix: soulpit removing players

src/creatures/npcs/npc.cpp
Reorganizes the cleanup logic within `Npc::closeAllShopWindows` to guarantee that `shopPlayers` is only cleared after all player shop windows have been properly closed. This approach avoids iterator invalidation issues and ensures efficient resource handling.
=> fix: possible crash in npc

data-global/monster/quests/cults_of_tibia/bosses/summons/dark_soul.lua, data-global/monster/quests/cults_of_tibia/bosses/the_corruptor_of_souls.lua, data-global/monster/quests/cults_of_tibia/bosses/the_source_of_corruption.lua, data-global/scripts/movements/others/dawnport_vocation_trial.lua, data-global/scripts/quests/cults_of_tibia/actions_bosses_levers.lua, data-global/scripts/quests/cults_of_tibia/actions_guilt.lua, data-global/scripts/quests/cults_of_tibia/creaturescripts_bosses_mission_cults.lua, data-global/scripts/quests/the_secret_library_quest/high_and_dry_isles/movements_stepIn.lua, data/events/scripts/player.lua
1.- Discarded a function in player.lua
2.- Added the fish condition on step in for the turtle in liberty bay.
3.- Created action script to use item guilt on target.
4.- Placed dark souls as spawn in the upper boss room. Corrected the corpse id of dark souls.
5.- Corrected the positions of the boss room in order to let spawn dark souls.
6.- Made vulnerable the stage 2 boss, however you must keep using guilt on him or he will revert to stage 1.
7.- Now this boss is playable! Have fun!
=> fix: the source of the corruption

data-global/scripts/custom/movement_trainer_entrance.lua, data/global.lua, data/modules/scripts/gamestore/gamestore.lua, data/scripts/talkactions/player/auto_loot.lua, data/scripts/talkactions/player/promotion.lua
- fixing description on how to use !autoloot
- updating name of the trainer creature to avoid erros when loading the custom otserver-br map (which brings the trainers)
- fixing prices of pray wildcard
- fixing variable used on !promotion it was referencing something that did not exist and therefore causing errors
- properly creating the trainers upon player entering the teleport, avoids creating more than 2 + avoid creating a monster where the player stands (given it checks if the monsters exists before creating)
=> fix: through the codebase

data-global/scripts/movements/rookgaard/movements_sword_of_fury.lua
Step in the rotworm sqm or spider cave sqm to make the sword dissapear, just like real tibia. No further coding available as this mistery has not been solved yet.
=> fix: The Sword of Fury

data-global/scripts/quests/the_rookie_guard/mission06_run_like_wolf.lua
Players cannot proceed in this part. Fixed the conditions to get the knive, You cannot enter this area without the storage anyways so a condition here to get the knive is redudant. Quest is fixed and none of the vital functions are affected.
=> fix: Run Like a Wolf

data/items/bags.xml, src/creatures/monsters/monster.cpp, src/items/items.cpp, src/items/items.hpp
This PR improve surprise bags system to work with % instead of ranges based
=> improve: surprise bags using % in chance instead of range

data-global/npc/ambassador manop.lua, data-global/scripts/quests/the_way_of_the_monk/actions_dawnport_shrines.lua
This pull request introduces functional and structural improvements to the The Way of the Monk quest, including:
Refactored actions_dawnport_shrines.lua:
Replaced hardcoded keys with Storage constants.
Added proper experience rewards and visual effects after using a shrine.
Improved quest storage tracking and validation to prevent repeated use of the same shrine.
Updated ambassador_manop.lua NPC behavior:
Dialogue flow now correctly reacts to shrine progress and questline state.
Ensures player receives vocation and teleport only after completing all shrine interactions.
Properly sets questline and questlog storage values on advancement.
=> fix: improvements to the way of the monk 

data-global/npc/awareness_of_the_emperor.lua, data-global/scripts/actions/tools/prepared_bucket.lua, data-global/scripts/quests/wrath_of_the_emperor/actions_mission10_a_message_of_freedom_sceptre.lua, data-global/startup/tables/chest.lua, data-global/world/world-npc.xml
Fixed a loop with firefighter achievement, ensures to get it only one time. Fixed bugs with wrath of emperor quest, now you can complete it. Corrected the name of NPC in spawn and file. Also now you can get the Godslayer Achievement.
=> Fixes: Warth of the Emperor Quest and Firefighter Achievement loop

data-global/monster/quests/primal_ordeal_quest/magma_bubble.lua
Added name = "charged ethereal ring" to the loot entry with id = 50149 in magma_bubble.lua.
This ensures consistency in the loot table and avoids potential issues in systems that rely on the item name field.
=> fix: add missing name to charged ethereal ring in loot 

src/creatures/players/player.cpp, src/creatures/players/player.hpp, src/game/game.cpp, src/game/game.hpp, src/server/network/protocol/protocolgame.cpp
This commit resolves an issue where a duplicate player instance was being created when a player confirmed the death screen ("ok") and was then kicked for exceeding the maximum packets per second. This bug caused two player objects to be active simultaneously, leading to unpredictable in-game behavior since the system was unable to determine which instance to interact with.
=> fix: duplicate player creation on death screen

src/server/network/protocol/protocolgame.cpp
**Summary:**
This pull request addresses an issue where a player's online status was not correctly updated on external websites after they died and respawned. Previously, after a player's death and subsequent respawn, their status in the players_online table was not updated, causing them to incorrectly appear offline.
**The Fix:**
I've added the following line to ProtocolGame::parsePacketDead in Protocolgame.cpp:
IOLoginData::updateOnlineStatus(player->getGUID(), true);
This ensures that after a player successfully respawns, their online status is correctly updated in the players_online table. As a result, the player.isOnline() method on websites will now accurately reflect the player's status.
=> improved: Player online status update after Death/Respawn

data/XML/outfits.xml, src/creatures/players/player.cpp
This PR ensures that outfit bonuses are applied only if the character is wearing the full addon.
For testing purposes, I have enabled the Citizen addon with full bonuses. The bonuses will be removed once the PR is merged.
=> improve: outfits bonuses

data-global/raids/thais/cyclops.xml
They spawn at wrong position and make game unplayable for new monks. This correction sets raid just as real tibia is.
=> fix: Thais Cyclops raid

src/creatures/combat/combat.cpp
This patch ensures that critical hits are restricted exclusively to player attacks.
Changes:
- Added explicit guards to disable critical chance and multipliers for monsters.
- Ensured CombatDamage is calculated per target to avoid state contamination.
- Prevented critical flags from being reused across multiple targets/attackers.
- Maintained monster attack multipliers without applying critical damage.
This resolves the issue where monsters could either trigger their own critical hits
or inherit a critical state from nearby player attacks.
=> fix: prevent monsters from triggering or inheriting critical hits

src/creatures/players/player.cpp
This change will fix the mantra attribute bonus on boots for vocation Monks
=> fix: mantra attribute bonus on boots

data-global/scripts/quests/rotten_blood_quest/actions_chagorz.lua, data-global/scripts/quests/rotten_blood_quest/actions_murcion.lua, data-global/scripts/quests/rotten_blood_quest/actions_vemiath.lua
This PR includes two fixes related to the quest **Rotten Blood**:
1. **Fix for boss teleports**:
- Adjusted the teleports to ensure players are correctly transported to the boss areas.
- Previous issues resulted in mispositioned teleports.
2. **Adjustment of the lever position**:
- Corrected the lever position to `{ x = 33079, y = 32333, z = 15 }`.
- The previous position was incorrect, causing failures in the boss cooldown.
- Players were unable to access the boss areas due to misconfigured teleports.
- The boss cooldown was not functioning correctly due to the incorrect lever position.
- Updated the teleports for the bosses in the quest **Rotten Blood**.
- Adjusted the lever position to ensure the correct functioning of the cooldown.
- Verified that the teleports lead players to the …
=> fix: adjust teleports for rotten blood bosses quest
